import { describe, it, expect, vi } from 'vitest'
import { render, screen } from '@testing-library/react'
import RootLayout, { metadata } from '@/app/layout'

// Mock CopilotKit
vi.mock('@copilotkit/react-core', () => ({
  CopilotKit: ({ children, runtimeUrl, agent }: any) => (
    <div data-testid="copilotkit-provider" data-runtime-url={runtimeUrl} data-agent={agent}>
      {children}
    </div>
  ),
}))

// Mock CSS imports
vi.mock('@/app/globals.css', () => ({}))
vi.mock('@copilotkit/react-ui/styles.css', () => ({}))

describe('RootLayout', () => {
  it('renders children inside CopilotKit provider', () => {
    render(
      <RootLayout>
        <div data-testid="child-content">Test Content</div>
      </RootLayout>
    )

    expect(screen.getByTestId('child-content')).toBeInTheDocument()
    expect(screen.getByText('Test Content')).toBeInTheDocument()
  })

  it('wraps children with CopilotKit provider', () => {
    render(
      <RootLayout>
        <div>Content</div>
      </RootLayout>
    )

    const provider = screen.getByTestId('copilotkit-provider')
    expect(provider).toBeInTheDocument()
  })

  it('configures CopilotKit with correct runtime URL', () => {
    render(
      <RootLayout>
        <div>Content</div>
      </RootLayout>
    )

    const provider = screen.getByTestId('copilotkit-provider')
    expect(provider).toHaveAttribute('data-runtime-url', '/api/copilotkit')
  })

  it('configures CopilotKit with correct agent name', () => {
    render(
      <RootLayout>
        <div>Content</div>
      </RootLayout>
    )

    const provider = screen.getByTestId('copilotkit-provider')
    expect(provider).toHaveAttribute('data-agent', 'my_agent')
  })

  it('renders multiple children correctly', () => {
    render(
      <RootLayout>
        <div data-testid="first">First</div>
        <div data-testid="second">Second</div>
      </RootLayout>
    )

    expect(screen.getByTestId('first')).toBeInTheDocument()
    expect(screen.getByTestId('second')).toBeInTheDocument()
  })

  it('passes through complex children', () => {
    render(
      <RootLayout>
        <nav>Navigation</nav>
        <main>Main Content</main>
        <footer>Footer</footer>
      </RootLayout>
    )

    expect(screen.getByText('Navigation')).toBeInTheDocument()
    expect(screen.getByText('Main Content')).toBeInTheDocument()
    expect(screen.getByText('Footer')).toBeInTheDocument()
  })
})

describe('metadata', () => {
  it('has correct title', () => {
    expect(metadata.title).toBe('Create Next App')
  })

  it('has correct description', () => {
    expect(metadata.description).toBe('Generated by create next app')
  })
})
